linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosimple
    - typecheck

linters-settings:
  errcheck:
    check-blank: true

issues:
  exclude-use-default: false
